feat: homeWork-2, sorry for late(
Letto228/Angular-learnjs-261023 pull request #36
Opened 2023-11-10 09:56 UTC by Solrud

Мне пришлось удалить в husky pre-commit скрипты, потому что у меня конфликты с prettier'ом.. я написал вопрос об этм в дискорд канал "angular-26102023"

2023-11-14 20:57 UTC, Letto228 requested changes
Привет!
Карточка хороша, молодец! Но есть нюанс: данные в твоей карточке статичны, они закреплены прямо в шаблоне. По ДЗ же подразумевалось, что данные в карточку будут подтягиваться из самого мока `productMock` при помощи `binding` и `interpolation`.

Давай переделаем так, чтобы данные в карточку все таки подтягивались напрямую из объекта `productMock`. Для работы с моком, конечно, потребуется сохранить его данные в шаблоне, ведь в шаблоне мы имеем доступ только до свойств класса компонента
```
export class CardComponent {
    readonly product = productMock;
    
    ...
}
```

2023-11-14 20:57 UTC, Letto228 commented on src/app/app.module.ts
> +import {CardModule} from './pages/products-list/card/card.module';
Нигде не используется?

2023-11-14 20:58 UTC, Letto228 commented
> Мне пришлось удалить в husky pre-commit скрипты, потому что у меня конфликты с prettier'ом.. я написал вопрос об этм в дискорд канал "angular-26102023"

Да, кажется, мы с тобой связались по данному вопросу, если нет и я ошибся, дай знать, пожалуйста. Или можно написать напрямую в дискорд, чтобы я быстрее среагировал

2023-11-15 04:10 UTC, Solrud commented
> > Мне пришлось удалить в husky pre-commit скрипты, потому что у меня конфликты с prettier'ом.. я написал вопрос об этм в дискорд канал "angular-26102023"
> 
> Да, кажется, мы с тобой связались по данному вопросу, если нет и я ошибся, дай знать, пожалуйста. Или можно написать напрямую в дискорд, чтобы я быстрее среагировал

Да. С тобой связывались. Насчет статических данных, сделаю как надо

2023-11-15 11:42 UTC, Solrud commented
Привет, доделал домашку!

2023-11-15 18:56 UTC, Letto228 reviewed
Отлично! Оставил пару вопросов, буду ждать твоего фидбека!

2023-11-15 18:56 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.html
> +        <p>Чудесный планшет, качественный, для всех видов программистов, тянет даже игрушки!</p>
Описание статично, оно не будет меняться при смене данных в моке)

2023-11-15 18:56 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.html
> +        <p [style.font-size.px]="20">{{product.name}}</p>
Почему тут решил binding использовать? Или просто тренировался с синтаксисом?

2023-11-15 18:56 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.html
> +        <div style="display: flex; gap: 1rem">
Почему так много используешь статичных инлайновых стилей?

2023-11-15 18:56 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.html
> +        <div style="display: flex; gap: 1rem">
Вот тут статейка есть на эту тему - https://habr.com/ru/companies/htmlacademy/articles/573768/

2023-11-15 18:56 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.ts
> +    rating = this.product.rating;
Почему рейтинг вынес в отдельное свойство?

2023-11-16 08:35 UTC, Solrud commented on src/app/pages/products-list/card/card.component.html
> +        <p>Чудесный планшет, качественный, для всех видов программистов, тянет даже игрушки!</p>
Это понятно) Его же нет в мойке. Я просто от себя добавил 😅

2023-11-16 08:35 UTC, Solrud commented on src/app/pages/products-list/card/card.component.html
> +        <p [style.font-size.px]="20">{{product.name}}</p>
Тренировался с синтаксисом

2023-11-16 08:36 UTC, Solrud commented on src/app/pages/products-list/card/card.component.html
> +        <div style="display: flex; gap: 1rem">
Да я знаю что это плохо. Но я тогда торопился. Постараюсь так не делать!

2023-11-16 08:39 UTC, Solrud commented on src/app/pages/products-list/card/card.component.ts
> +    rating = this.product.rating;
Даже не знаю, если честно)

2023-11-16 09:07 UTC, Solrud commented
> Отлично! Оставил пару вопросов, буду ждать твоего фидбека!

Фидбек готов)

2023-11-16 09:08 UTC, Solrud commented on src/app/app.module.ts
> +import {CardModule} from './pages/products-list/card/card.module';
Не понял. Что не используется?

2023-11-18 07:07 UTC, Letto228 commented on src/app/app.module.ts
> +import {CardModule} from './pages/products-list/card/card.module';
`CardModule` - ты его импортируешь в TS файл, но нигде в этом файле не используешь

2023-11-18 07:07 UTC, Letto228 commented on src/app/app.module.ts
> +import {CardModule} from './pages/products-list/card/card.module';
`CardModule` - ты его импортируешь в TS файл, но нигде в этом файле не используешь

2023-11-18 07:09 UTC, Letto228 commented
Все супер - увидел 👍. Вот тут ответил на вопрос - https://github.com/Letto228/Angular-learnjs-261023/pull/36#discussion_r1398113456

2023-11-18 07:23 UTC, closed without merging